version: '3.8'
services:
  web:
    build: .
    command: ./start.sh
    volumes:
      - .:/usr/src/app
      - /home/stock/Documents/UNICEF/test 100/:/usr/src/app/media
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/dbname
      - MEDIA_FILES=/usr/src/app/media 
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: dbname
  redis:
    restart: always
    image: redis
    expose:
      - "6379"

volumes:
  postgres_data:
