version: '3.8'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
      - ~/Documents/UNICED/test 100/:/usr/src/app/media
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/dbname
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: dbname
  redis:
    image: redis:7

  # Celery Beat service
  celery-beat:
    image: python:3.10-slim-buster
    volumes:
      - .:/code
    command: celery -A face_rec beat -l INFO
    depends_on:
      - redis
      - db

  # Celery Worker service
  celery-worker:
    image: python:3.10-slim-buster
    volumes:
      - .:/code
    command: celery -A face_rec worker -l info
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
