# Generated by Django 3.2.23 on 2023-12-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Individual",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("photo", models.ImageField(upload_to="individual_photos/")),
            ],
            options={
                "unique_together": {("first_name", "last_name")},
            },
        ),
    ]
