# Generated by Django 3.2.23 on 2023-12-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recognizeapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="individual",
            name="face_encoding",
            field=models.TextField(blank=True, null=True),
        ),
    ]
